Language:
  UseClientLanguage: false
  DefaultLanguage: "english"
Chat:
  PrefixChat:
    Enabled: true
  ColorChat:
    Enabled: true
Join:
  Spawn:
    TeleportOnFirstJoin: true
    TeleportOnJoin: true
  Message:
    Enabled: true
    SendMessage: false
    Message: "<Color:Highlight><SENDER> <Color:Message>joined the server."
  Sound:
    Enabled: false
    Sound: "block.note_block.pling"
Quit:
  Message:
    Enabled: true
    SendMessage: false
    Message: "<Color:Error.Highlight><SENDER> <Color:Error.Message>left the server."
  Sound:
    Enabled: false
    Sound: "block.note_block.harp"
UserData:
  Compression:
    Enabled: true
    Description: "Wether to enable gzip compression for UserData files. This can reduce disk space, but may increase CPU usage."
MinecraftDiscordChat:
  Enabled: false
  WebhookUrl: ""
AwayFromKeyboard:
  Enabled: false
  Description: "Kinda aggressive, needs to be adjusted in future updates"
DeveloperJoin:
  NotifyDeveloper:
    Enabled: true
    Description: "Notifies me, if you're running ServerSystem :)"
UpdateChecker:
  AutoUpdate: true
  Type:
    Value: MAIN
    Description: "Where the plugin checks for updates. Currently available: Disabled, Hangar, Main (Main = My own server)"