name: ServerSystem
version: 1.7.5
main: me.entity303.serversystem.main.ServerSystem
api-version: 1.13
authors: [Entity303]
load: POSTWORLD
loadbefore:
  - AntiPluginLookUp
  - Vault
softdepend:
  - Essentials
  - PlotSquared
  - Vault
  - PlaceholderAPI
