name: ServerSystem
version: '${project.version}'
main: me.testaccount666.serversystem.ServerSystem
api-version: '1.21'
authors: [ TestAccount666 ]
softdepend:
  - NBTAPI
  - PlaceholderAPI
loadbefore:
  - Vault
libraries:
  - io.github.classgraph:classgraph:4.8.181
  - net.bytebuddy:byte-buddy:1.17.7
  - com.zaxxer:HikariCP:7.0.2
  - com.h2database:h2:2.4.240
