name: ServerSystem
version: '${project.version}'
main: me.testaccount666.serversystem.ServerSystem
api-version: '1.21'
authors: [ TestAccount666 ]
depend: [ NBTAPI ]
softdepend:
  - Vault
libraries:
  - io.github.classgraph:classgraph:4.8.180
  - net.bytebuddy:byte-buddy:1.17.5
  - com.zaxxer:HikariCP:6.3.0