name: Feature request
description: Suggest an idea for ServerSystem
title: "[Feature Request] "
labels: [enhancement]
assignees:
  - Test-Account666

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please complete all sections so we can better understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. "I'm always frustrated when..."
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "I would like it if..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Alternatively, it could..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues to avoid duplicates
          required: true
        - label: I have provided as much detail as I can
          required: true
        - label: I understand incomplete reports may be harder to resolve
          required: true
